version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - mdaubie
  # Python
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - mdaubie
