name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"
          cache: "pip"

      - name: Install commitizen
        run: pip install commitizen

      - name: Generate release notes
        run: cz changelog ${{ github.ref_name }} --dry-run > RELEASE_NOTES.md

      - name: Detect prerelease
        id: prerelease
        run: |
          TAG="${{ github.ref_name }}"
          if [[ "$TAG" =~ (-|a|b|rc) ]]; then
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v3
        with:
          name: ${{ github.ref_name }}
          body_path: RELEASE_NOTES.md
          generate_release_notes: false
          prerelease: ${{ steps.prerelease.outputs.is_prerelease }}
          make_latest: ${{ !steps.prerelease.outputs.is_prerelease }}

  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/muxwell/${{ github.ref_name }}
    permissions:
      id-token: write # OIDC for PyPI

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: true

      - name: Build package
        run: uv build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
